# Generated by Django 6.0.7 on 2026-08-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_utilisateur_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='organisation',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='accounts.organisation'),
        ),
    ]
