# Generated by Django 6.0.7 on 2026-07-09 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vague', models.DateTimeField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurVague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.vague')),
            ],
            options={
                'unique_together': {('vague', 'utilisateur')},
            },
        ),
    ]
