# Generated by Django 6.0.7 on 2026-07-17 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_alter_formation_createur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vague',
            old_name='date_vague',
            new_name='debut',
        ),
        migrations.AddField(
            model_name='vague',
            name='fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
