# Generated by Django 6.0.7 on 2026-08-03 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_utilisateur_organisation'),
        ('formations', '0004_rename_date_vague_vague_debut_vague_fin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='createur',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur__type_utilisateur': 'formateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
