# Generated by Django 6.0.7 on 2026-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_formation_organisation_alter_formation_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vague',
            name='nom_vague',
            field=models.CharField(default='Nouvelle Session', max_length=255),
        ),
    ]
