# Generated by Django 6.0.7 on 2026-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_vague_nom_vague'),
        ('quizzes', '0018_alter_utilisateurquiz_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vague',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='vagues_assignees', to='quizzes.quiz'),
        ),
    ]
