# Generated by Django 6.0.7 on 2026-07-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valiny',
            name='corrigee',
        ),
        migrations.RemoveField(
            model_name='valiny',
            name='user_valiny',
        ),
        migrations.AddField(
            model_name='valiny',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valiny',
            name='reponse_ouverte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valiny',
            name='reponses_choisies',
            field=models.ManyToManyField(blank=True, help_text="Les options sélectionnées par l'apprenant pour les QCM/QCU", to='quizzes.reponse'),
        ),
        migrations.AlterField(
            model_name='valiny',
            name='vrai_ou_faux',
            field=models.BooleanField(default=False),
        ),
    ]
