# Generated by Django 6.0.7 on 2026-07-10 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_valiny_corrigee_remove_valiny_user_valiny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurquiz',
            name='date_tentative',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateurquiz',
            name='score_obtenu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='utilisateurquiz',
            name='termine',
            field=models.BooleanField(default=False),
        ),
    ]
