# Generated by Django 6.0.7 on 2026-07-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_utilisateurquiz_date_tentative_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='bareme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.bareme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='type_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.typequestion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question', 'type_question', 'bareme')},
        ),
    ]
