# Generated by Django 6.0.7 on 2026-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quizquestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrigee',
            name='est_correct',
            field=models.BooleanField(default=False, help_text='Cochez si cette réponse est la bonne.'),
        ),
    ]
