# Generated by Django 6.0.7 on 2026-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_corrigee_est_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurquiz',
            name='heure_debut',
            field=models.DateTimeField(blank=True, help_text="Heure à laquelle l'étudiant a commencé le quiz", null=True),
        ),
    ]
