# Generated by Django 6.0.7 on 2026-07-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_utilisateurquiz_heure_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrigee',
            name='explication',
            field=models.TextField(blank=True, help_text='Explication affichée pour ce choix spécifique lors de la correction.', null=True),
        ),
    ]
