# Generated by Django 6.0.7 on 2026-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_corrigee_explication'),
    ]

    operations = [
        migrations.AddField(
            model_name='typequestion',
            name='code',
            field=models.CharField(help_text='Code système immuable (ex: QCU, QCM, OUV)', max_length=10, null=True, unique=True),
        ),
    ]
