# Generated by Django 6.0.7 on 2026-07-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_typequestion_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurquiz',
            old_name='date_tentative',
            new_name='date_assignation',
        ),
    ]
