# Generated by Django 6.0.7 on 2026-07-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_rename_date_tentative_utilisateurquiz_date_assignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_fermeture',
            field=models.DateTimeField(blank=True, help_text='Date et heure limites pour démarrer le quiz', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_ouverture',
            field=models.DateTimeField(blank=True, help_text='Date et heure à partir desquelles le quiz est accessible', null=True),
        ),
    ]
