# Generated by Django 6.0.7 on 2026-08-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_question_is_active_quiz_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='titre',
            field=models.CharField(default='Quiz sans titre', help_text='Le nom ou le titre de ce quiz', max_length=255),
        ),
    ]
