# Generated by Django 6.0.7 on 2026-08-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_quiz_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(default='draft', help_text='draft (brouillon), published (publié), deleted (supprimé)', max_length=50),
        ),
    ]
