# Generated by Django 6.0.7 on 2026-08-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_utilisateur_organisation'),
        ('quizzes', '0013_alter_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation'),
        ),
    ]
