# Generated by Django 6.0.7 on 2026-09-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_question_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='valiny',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
    ]
