# Generated by Django 6.0.7 on 2026-09-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_formation_organisation_alter_formation_createur'),
        ('quizzes', '0015_valiny_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurquiz',
            name='vague',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.vague'),
        ),
    ]
