# Generated by Django 6.0.7 on 2026-09-10 05:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_vague_nom_vague'),
        ('quizzes', '0017_valiny_vague'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utilisateurquiz',
            unique_together={('quiz', 'utilisateur', 'vague')},
        ),
    ]
