services:
  db:
    image: postgres:15-alpine
    container_name: qst_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    container_name: qst_django
    command: gunicorn backdev.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}  
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432

volumes:
  postgres_data: